import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import BonusList from "../components/Bonus";
import MyHero from "../components/MyHero";
import UnlockedHeroes from "../components/UnlockedHeroes";
import { bonuses } from "../data/bonuses";
import styles from "../styles/Home.module.css";

const tempBonuses = [...bonuses];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MyHero />
        <UnlockedHeroes />
        <BonusList bonuses={tempBonuses} />
      </main>

      <footer className="sticky bottom-0 bg-white italic">footer tbd</footer>
    </div>
  );
};

export default Home;
